# Generated by Django 4.2.21 on 2025-07-03 06:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_remove_contract_client_name_remove_contract_end_date_and_more'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.AddField(
            model_name='invoice',
            name='account_holder',
            field=models.CharField(default='', max_length=100, verbose_name='口座名義'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='account_number',
            field=models.CharField(default='', max_length=20, verbose_name='口座番号'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_name',
            field=models.CharField(default='', max_length=100, verbose_name='金融機関名'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='branch_name',
            field=models.CharField(default='', max_length=100, verbose_name='支店名'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='contracts.contract', verbose_name='契約'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_due_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='支払期日'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='registration_number',
            field=models.CharField(default='', max_length=50, verbose_name='登録番号'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sent_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='送信日'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default='', max_length=50, verbose_name='請求書番号'),
        ),
    ]
