# Generated by Django 4.2.21 on 2025-07-04 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_invoice_amount_remove_invoice_due_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': '請求基本情報', 'verbose_name_plural': '請求基本情報'},
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='品目')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='単価')),
                ('basic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice', verbose_name='請求基本情報')),
            ],
            options={
                'verbose_name': '請求明細行',
                'verbose_name_plural': '請求明細行',
            },
        ),
    ]
