# Generated by Django 4.2.21 on 2025-05-27 13:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='title',
        ),
        migrations.AddField(
            model_name='contract',
            name='client_address',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='契約先住所'),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_company',
            field=models.CharField(default='', max_length=255, verbose_name='契約先会社名'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='契約終了日'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='契約開始日'),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時'),
        ),
        migrations.AddField(
            model_name='contract',
            name='deduction_unit_price',
            field=models.PositiveIntegerField(default=0, verbose_name='控除単価（円/時）'),
        ),
        migrations.AddField(
            model_name='contract',
            name='employee_name',
            field=models.CharField(default='', max_length=255, verbose_name='社員名'),
        ),
        migrations.AddField(
            model_name='contract',
            name='overtime_unit_price',
            field=models.PositiveIntegerField(default=0, verbose_name='超過単価（円/時）'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_site_days',
            field=models.PositiveIntegerField(default=0, verbose_name='支払いサイト（日）'),
        ),
        migrations.AddField(
            model_name='contract',
            name='project_name',
            field=models.CharField(default='', max_length=255, verbose_name='案件名'),
        ),
        migrations.AddField(
            model_name='contract',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, verbose_name='単価（万円/月）'),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='contract',
            name='work_style',
            field=models.CharField(choices=[('remote', 'リモートワーク'), ('onsite', '常駐'), ('hybrid', 'ハイブリッド')], default='onsite', max_length=20, verbose_name='働き方'),
        ),
        migrations.AddField(
            model_name='contract',
            name='working_hours_max',
            field=models.PositiveIntegerField(default=0, verbose_name='上限時間（h/月）'),
        ),
        migrations.AddField(
            model_name='contract',
            name='working_hours_min',
            field=models.PositiveIntegerField(default=0, verbose_name='下限時間（h/月）'),
        ),
        migrations.CreateModel(
            name='ContractManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='担当者氏名')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='contracts.contract')),
            ],
        ),
        migrations.CreateModel(
            name='ContractHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='contracts.contract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
